# -*- coding: utf-8 -*-
"""Final Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SH98aLgUpTkeIYwQTMs50ycHwGFIUai4

# Bike demand Project
"""

!pip install --upgrade factor_analyzer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.mixture import GaussianMixture
from sklearn.linear_model import LogisticRegression, ElasticNet
from sklearn.model_selection import TimeSeriesSplit
# confusion_matrix was missing before -> logistic CV cell crashed
from sklearn.metrics import roc_auc_score, accuracy_score, confusion_matrix
from sklearn.metrics import mean_squared_error, r2_score
from factor_analyzer.rotator import Rotator
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

"""- Rental counts: cnt; high_demand, a derived binary label.
- Demand components: casual, registered, cnt. Since cnt equals casual plus registered, avoid using casual and registered as predictors when predicting cnt.
- Time and calendar: dteday, season, yr, mnth, hr, holiday, weekday, workingday.
- Weather: weathersit, temp, atemp, hum, windspeed
"""

data = pd.read_csv("/content/drive/MyDrive/Stats Final/bike_sharing_hourly.csv")
data["dteday"] = pd.to_datetime(data["dteday"])
data = data.sort_values("dteday")
data.head()

#No NA´s
data.isna().sum()

"""## Discriptive data exploration and visualization."""

# Keep weathersit and season as int so the Pearson heatmap below treats them properly
# (only weekday/yr/high_demand go to category, just for nicer legends).
data["weekday"]     = data["weekday"].astype("category")
data["yr"]          = data["yr"].astype("category")
data["high_demand"] = data["high_demand"].astype("category")

data["holiday"]    = data["holiday"].astype(int)
data["workingday"] = data["workingday"].astype(int)
data.head()

#Lets see how cnt behaves
plt.figure(figsize=(8, 5))
sns.histplot(data["cnt"], bins=40, kde=True)
plt.title("Distribution of Bike Demand")
plt.xlabel("Total rentals")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

corr_cols = [ "cnt", "temp", "atemp", "hum", "windspeed", "holiday", "workingday", "hr", "mnth", "season", "weathersit"]

pearson_corr = data[corr_cols].corr(method="pearson")
plt.figure(figsize=(8, 6))
sns.heatmap(
    pearson_corr,
    annot=True,
    cmap="coolwarm",
    center=0,
    fmt=".2f",
    linewidths=0.5,
    square=True
)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()

# Drop col atemp since is very correlated with temp
data = data.drop(columns= ['atemp', "instant"])
data.head()

"""Bike demand shows a clear time pattern. Demand is very low overnight, rises sharply in the morning, peaks around 8am, and increases again in the late afternoon, especially around 5–6pm. This suggests a strong commuting pattern.

Across weekdays, differences exist but are smaller than the hourly differences. Average demand is slightly lower at the beginning of the week and somewhat higher toward Thursday/Friday.

By season, the differences are meaningful: season 1 has the lowest average demand, while season 3 has the highest, suggesting strong seasonality.

Weather also matters clearly. As weather conditions worsen, average demand falls. weathersit = 1 has the highest demand, while weathersit = 3 is much lower. weathersit = 4 has very few observations, so it should not be overinterpreted.
"""

hour_workingday = data.groupby(["workingday", "hr"], observed=True)["cnt"].mean().reset_index()

plt.figure(figsize=(7, 5))
sns.lineplot(data=hour_workingday, x="hr", y="cnt", hue="workingday", marker="o")
plt.title("Average Demand by Hour and Working Day")
plt.xlabel("Hour")
plt.ylabel("Average rentals")
plt.tight_layout()
plt.show()

# yr is 0/1 in the raw data — relabel for a readable legend
monthly_yr = (
    data.groupby(["yr", "mnth"], observed=True)["cnt"]
    .mean()
    .reset_index()
)
monthly_yr["yr"] = monthly_yr["yr"].astype(int).map({0: 2011, 1: 2012})

plt.figure(figsize=(7, 5))
sns.lineplot(data=monthly_yr, x="mnth", y="cnt", hue="yr", marker="o")
plt.title("Average Hourly Demand by Month, 2011 vs 2012")
plt.xlabel("Month")
plt.ylabel("Mean rentals per hour")
plt.xticks(range(1, 13))
plt.tight_layout()
plt.show()

"""## Multivariate structure analysis

We transformed hr and mnth into sine and cosine variables because both are cyclical time variables. For example, hour 23 and hour 0 are close in the daily cycle, and December and January are close in the yearly cycle, even though their raw numeric values are far apart. Using the raw values could make distance-based methods such as PCA, clustering, or Gaussian mixture models treat these observations as artificially distant. The sine and cosine transformations map each hour or month onto a circle, preserving the cyclical structure of time. Both sine and cosine are needed because using only one would lose information: different hours or months can have the same sine or cosine value. Together, they give each time point a unique position on the cycle while keeping neighboring times close to each other.
"""

data["hr_sin"] = np.sin(2 * np.pi * data["hr"] / 24)
data["hr_cos"] = np.cos(2 * np.pi * data["hr"] / 24)
data["mnth_sin"] = np.sin(2 * np.pi * data["mnth"] / 12)
data["mnth_cos"] = np.cos(2 * np.pi * data["mnth"] / 12)

feature_cols = ["hr_sin", "hr_cos", "mnth_sin", "mnth_cos",
                "temp", "hum", "windspeed",
                "workingday", "holiday", "weathersit"]

X = data[feature_cols].values
X_scaled = StandardScaler().fit_transform(X)

pca = PCA().fit(X_scaled)
X_pca = pca.transform(X_scaled)

# Variance explained
plt.figure(figsize=(7, 5))
plt.plot(range(1, len(feature_cols)+1), np.cumsum(pca.explained_variance_ratio_), marker="o")
plt.axhline(0.8, ls="--", color="gray")
plt.xlabel("Number of components"); plt.ylabel("Cumulative variance explained")
plt.title("PCA scree (cumulative)"); plt.tight_layout(); plt.show()

ks = range(2, 9)
wcss, sil = [], []
for k in ks:
    km = KMeans(n_clusters=k, random_state=123, n_init=20).fit(X_pca)
    wcss.append(km.inertia_)
    sil.append(silhouette_score(X_pca, km.labels_, sample_size=5000, random_state=123))

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
axes[0].plot(list(ks), wcss, marker="o"); axes[0].set_title("Elbow (WCSS)")
axes[0].set_xlabel("K"); axes[0].set_ylabel("WCSS")
axes[1].plot(list(ks), sil, marker="o"); axes[1].set_title("Average silhouette")
axes[1].set_xlabel("K"); axes[1].set_ylabel("Silhouette")
plt.tight_layout(); plt.show()

# Choose 6 components based on cumulative variance ≥ 80%
pca = PCA(n_components=6)
X_pca = pca.fit_transform(X_scaled)
print(f"Variance retained: {pca.explained_variance_ratio_.sum():.3f}")
loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
loadings_df = pd.DataFrame(
    loadings,
    index = feature_cols,
    columns=[f"PC{i+1}" for i in range(loadings.shape[1])])
loadings_df.round(3)

# Varimax rotation
rotator = Rotator(method="varimax")
rotated_loadings = rotator.fit_transform(loadings)

rotated_loadings_df = pd.DataFrame(
    rotated_loadings,
    index=feature_cols,
    columns=[f"RC{i+1}" for i in range(rotated_loadings.shape[1])]
)

plt.figure(figsize=(7, 5))
sns.heatmap(rotated_loadings_df,
            annot=True, fmt=".2f",
            cmap="RdBu_r", center=0, vmin=-1, vmax=1,
            cbar_kws={"label": "Loading"},
            linewidths=0.5, linecolor="white")
plt.title("Varimax-rotated PCA Loadings (6 factors)")
plt.xlabel("Rotated Component"); plt.ylabel("Original Feature")
plt.tight_layout(); plt.show()

"""The varimax rotation yields six interpretable dimensions. RC1 captures a seasonal-temperature factor, mainly driven by temperature and the cosine transformation of month. RC2 and RC6 jointly represent the hour-of-day cycle, since they load strongly on the sine and cosine transformations of hour, respectively. RC3 captures a calendar effect, separating working days from holidays. RC4 is a weather-quality factor, with strong positive loadings on weather situation and humidity, suggesting worse or more humid weather conditions. RC5 captures the second dimension of the annual seasonal cycle, mainly driven by the sine transformation of month. Overall, the rotation organizes the original predictors into economically meaningful groups: seasonality, time of day, calendar structure, and weather conditions."""

km = KMeans(n_clusters=3, random_state=123, n_init=20)
data["cluster"] = km.fit_predict(X_pca)
# Relabel clusters 0/1/2 by mean cnt (low → high)
order = data.groupby("cluster")["cnt"].mean().sort_values().index
data["cluster"] = data["cluster"].map({old: new for new, old in enumerate(order)})

profile = data.groupby("cluster").agg(
    n=("cnt", "size"),
    mean_cnt=("cnt", "mean"),
    median_cnt=("cnt", "median"),
    mean_hr=("hr", "mean"),
    mean_temp=("temp", "mean"),
    mean_hum=("hum", "mean"),
    pct_workingday=("workingday", "mean"),
    pct_holiday=("holiday", "mean"),
    mean_weathersit=("weathersit", "mean"),
).sort_values("mean_cnt").round(2)
print(profile)

"""Cluster 2 → mean_cnt ≈ 272, high demand → warm hours (temp ≈ 0.69) with mild weather.
Cluster 1 → mean_cnt ≈ 179, medium demand → cold but clear hours (temp ≈ 0.35, weathersit ≈ 1.2), mostly cold months 1–4 and 11–12.
Cluster 0 → mean_cnt ≈ 108, low demand → driven less by temperature (temp ≈ 0.42) and more by poor weather (mean weathersit ≈ 1.9, humidity ≈ 0.81), concentrated in early-morning and overnight hours.
"""

# Dominant cluster per (hour, month) cell
grid = (data.groupby(["mnth", "hr"])["cluster"]
            .agg(lambda x: x.mode()[0])
            .unstack("hr"))

plt.figure(figsize=(12, 5))
sns.heatmap(grid, cmap="tab10", cbar_kws={"label": "Dominant cluster"})
plt.title("Dominant Cluster by Month × Hour")
plt.xlabel("Hour"); plt.ylabel("Month")
plt.tight_layout(); plt.show()

data.tail()

"""### GMM model

"""

gmm_cov_results = {"spherical": {"bic": [], "aic": []},
                   "diag":      {"bic": [], "aic": []},
                   "full":      {"bic": [], "aic": []}}

ks = range(2, 9)
for cov_type in gmm_cov_results:
    for k in ks:
        gmm = GaussianMixture(n_components=k, covariance_type=cov_type,
                              random_state=123, n_init=20).fit(X_pca)
        gmm_cov_results[cov_type]["bic"].append(gmm.bic(X_pca))
        gmm_cov_results[cov_type]["aic"].append(gmm.aic(X_pca))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for cov_type, marker in zip(gmm_cov_results, ["o", "s", "^"]):
    axes[0].plot(ks, gmm_cov_results[cov_type]["bic"], marker=marker, label=cov_type)
    axes[1].plot(ks, gmm_cov_results[cov_type]["aic"], marker=marker, label=cov_type)
axes[0].set_title("BIC by K and covariance type"); axes[0].set_xlabel("K"); axes[0].legend()
axes[1].set_title("AIC by K and covariance type"); axes[1].set_xlabel("K"); axes[1].legend()
plt.tight_layout(); plt.show()

"""Spherical covariance appears too restrictive for this application because it imposes isotropic clusters, while the diagonal model consistently achieves lower AIC and BIC. The full covariance model achieves the lowest information criteria, but its irregular pattern across K suggests potential instability or overfitting. Therefore, a diagonal covariance structure provides a reasonable compromise between flexibility, parsimony, and interpretability."""

# Stability check across 20 seeds for the diagonal GMM
# (previous version recorded the wrong cov_type label — leaked from the cell above)
rows = []
for k in range(2, 9):
    for seed in range(20):
        gmm = GaussianMixture(n_components=k, covariance_type="diag",
                              random_state=seed, n_init=10,
                              reg_covar=1e-6).fit(X_pca)
        rows.append({
            "k": k,
            "seed": seed,
            "bic": gmm.bic(X_pca),
            "aic": gmm.aic(X_pca),
            "converged": gmm.converged_,
            "lower_bound": gmm.lower_bound_,
        })

stability = pd.DataFrame(rows)
stability.groupby("k").agg(
    mean_bic=("bic", "mean"),
    sd_bic=("bic", "std"),
    min_bic=("bic", "min"),
    max_bic=("bic", "max"),
    convergence_rate=("converged", "mean"),
).round(2)

"""The diagonal GMM converges reliably across all values of K, with a convergence rate of 100%. The BIC decreases monotonically from K = 2 to K = 8, indicating that additional mixture components improve statistical fit. However, since the purpose of the clustering exercise is to identify broad and interpretable demand regimes rather than maximize density fit, I do not rely on BIC alone. Since Clustering alone gave us a clear idea before, we would like to test wethers a two or three component diagonal GMM remains useful as a parsimonious representation of low-, medium-, and high-demand regimes, while higher values of K likely split these broad regimes into more granular subpatterns."""

for k in [2, 3]:
    gmm = GaussianMixture(
        n_components=k,
        covariance_type="diag",
        random_state=123,
        n_init=20,
        reg_covar=1e-6
    )

    labels = gmm.fit_predict(X_pca)
    shares = pd.Series(labels).value_counts(normalize=True).sort_index()

    print(f"\nK = {k}")
    print(shares.round(3))

for k in [2, 3]:
    gmm = GaussianMixture(
        n_components=k,
        covariance_type="diag",
        random_state=123,
        n_init=20,
        reg_covar=1e-6
    )

    gmm.fit(X_pca)
    probs = gmm.predict_proba(X_pca)
    max_probs = probs.max(axis=1)

    print(f"\nK = {k}")
    print("Mean max probability:", round(max_probs.mean(), 3))
    print("Pct uncertain:", round((max_probs < 0.70).mean(), 3))

"""Applying this logic here: K=2 produces a degenerate partition (97% / 3%) that captures outliers rather than demand regimes, with a mean posterior probability of 1.0 indicating that nearly all observations are pinned to the dominant component — a sign of an unbalanced fit, not a clean separation. K=3 yields two balanced components (57% / 40%) plus a small residual cluster, with mean posterior probability dropping to 0.87 and 15% of observations near a decision boundary, which is the signature of a model discriminating between genuine groups. We therefore retain K=3 as the final choice, consistent with the K-means selection and prioritizing interpretability of demand regimes over marginal BIC improvement."""

gmm = GaussianMixture(n_components=3, covariance_type="diag",
                      random_state=123, n_init=20, reg_covar=1e-6)
data["gmm"] = gmm.fit_predict(X_pca)

# Relabel GMM same way as K-means so 0 = low, 2 = high (otherwise label numbers are random)
order = data.groupby("gmm")["cnt"].mean().sort_values().index
data["gmm"] = data["gmm"].map({old: new for new, old in enumerate(order)})

profile = data.groupby("gmm").agg(
    n=("cnt", "size"),
    mean_cnt=("cnt", "mean"),
    median_cnt=("cnt", "median"),
    mean_hr=("hr", "mean"),
    mean_temp=("temp", "mean"),
    mean_hum=("hum", "mean"),
    pct_workingday=("workingday", "mean"),
    pct_holiday=("holiday", "mean"),
    mean_weathersit=("weathersit", "mean"),
).sort_values("mean_cnt").round(2)
print(profile)

# Dominant cluster per (hour, month) cell
grid = (data.groupby(["mnth", "hr"])["gmm"]
            .agg(lambda x: x.mode()[0])
            .unstack("hr"))

plt.figure(figsize=(12, 5))
sns.heatmap(grid, cmap="tab10", cbar_kws={"label": "Dominant cluster"})
plt.title("Dominant Cluster by Month × Hour")
plt.xlabel("Hour"); plt.ylabel("Month")
plt.tight_layout(); plt.show()

print(pd.crosstab(data["cluster"], data["gmm"]))

"""This cross-tab compares K-means (rows) and the diagonal-covariance GMM (columns), both now ordered 0 → 2 by mean demand. The two methods show partial agreement. The extreme regimes coincide closely: most of K-means cluster 0 (low demand) is also in GMM 0, and most of K-means cluster 2 (high demand) is also in GMM 2. The middle K-means cluster does not survive as a separate group in GMM: it is split between the low and high components. GMM-diag therefore collapses the low and medium tiers into the low component while preserving the high-demand tier, and isolates a small third component composed mainly of holiday observations — a calendar-specific group that K-means distributes across its three demand-based clusters. The difference between the methods is not driven by GMM's covariance flexibility, since diag and K-means make similar assumptions about cluster shape, but by the absence of a balanced-size constraint in GMM: K-means tends to produce clusters of comparable size, while GMM allows one component to remain small and the other two to absorb mass unevenly. The takeaway is that the low and high demand regimes are robust across methods, while the existence of a distinct middle tier depends on the balanced-size assumption, and that GMM is sensitive to a calendar dimension (holidays) that K-means does not isolate.

## Supervised Learning
"""

# Unit-variance rotated factor scores: divide X_pca by sqrt(eigenvalues) before rotating,
# so the 6 factors share the same scale and coefficient magnitudes are comparable.
R = rotator.rotation_
X_rot = (X_pca / np.sqrt(pca.explained_variance_)) @ R

rot_cols = ["RC1_heat", "RC2_hr_sin", "RC3_calendar",
            "RC4_weather", "RC5_mnth_sin", "RC6_hr_cos"]
X_rot_df = pd.DataFrame(X_rot, columns=rot_cols, index=data.index)
X_rot_df.head()

y = (data["high_demand"] == "High").astype(int) #high =1
y.head()

X_features = data[feature_cols].values
y = (data["high_demand"] == "High").astype(int).values

tscv = TimeSeriesSplit(n_splits=5)
fold_rows = []

for fold, (tr_idx, te_idx) in enumerate(tscv.split(X_features)):
    Xtr_raw, Xte_raw = X_features[tr_idx], X_features[te_idx]
    ytr, yte = y[tr_idx], y[te_idx]

    sc = StandardScaler().fit(Xtr_raw)
    Xtr_s, Xte_s = sc.transform(Xtr_raw), sc.transform(Xte_raw)

    pca_k = PCA(n_components=6).fit(Xtr_s)
    Xtr_pca = pca_k.transform(Xtr_s)
    Xte_pca = pca_k.transform(Xte_s)

    loadings_k = pca_k.components_.T * np.sqrt(pca_k.explained_variance_)
    rotator_k = Rotator(method="varimax")
    rotator_k.fit_transform(loadings_k)
    R_k = rotator_k.rotation_

    # Same unit-variance scaling as in cell above so coefs are comparable across folds AND columns
    Xtr_rot = (Xtr_pca / np.sqrt(pca_k.explained_variance_)) @ R_k
    Xte_rot = (Xte_pca / np.sqrt(pca_k.explained_variance_)) @ R_k

    clf = LogisticRegression(penalty=None, max_iter=2000).fit(Xtr_rot, ytr)
    proba = clf.predict_proba(Xte_rot)[:, 1]
    pred  = (proba >= 0.5).astype(int)

    tn, fp, fn, tp = confusion_matrix(yte, pred).ravel()
    fold_rows.append({
        "fold":        fold,
        "auc":         roc_auc_score(yte, proba),
        "acc":         accuracy_score(yte, pred),
        "sensitivity": tp / (tp + fn) if (tp + fn) > 0 else np.nan,
        "specificity": tn / (tn + fp) if (tn + fp) > 0 else np.nan,
        "precision":   tp / (tp + fp) if (tp + fp) > 0 else np.nan,
        # store per-fold coefficients so the stability claim below is reproducible
        **{f"coef_{i+1}": c for i, c in enumerate(clf.coef_[0])},
    })

logit_results = pd.DataFrame(fold_rows)
metric_cols = ["fold", "auc", "acc", "sensitivity", "specificity", "precision"]
print(logit_results[metric_cols].round(3))
print(f"\nMean AUC: {logit_results['auc'].mean():.3f}   "
      f"Mean Acc: {logit_results['acc'].mean():.3f}")
print(f"Mean Sensitivity: {logit_results['sensitivity'].mean():.3f}   "
      f"Mean Specificity: {logit_results['specificity'].mean():.3f}")

# Coefficient stability across folds (|mean| / sd)
coef_cols = [f"coef_{i+1}" for i in range(6)]
coef_stability = pd.DataFrame({
    "factor": rot_cols,
    "mean":   logit_results[coef_cols].mean().values,
    "sd":     logit_results[coef_cols].std().values,
})
coef_stability["abs_mean_over_sd"] = coef_stability["mean"].abs() / coef_stability["sd"]
print("\nCoefficient stability (sorted by |mean|/sd):")
print(coef_stability.sort_values("abs_mean_over_sd", ascending=False).round(3))

"""The logistic regression on the 6 rotated factors achieves a mean AUC of **0.884** across the 5 time-series CV folds (range 0.83–0.94), so the factor representation captures most of the predictive signal. Sensitivity (0.60) is well below specificity (0.92): the model is biased toward predicting "Low", especially in the early folds, where the training window covers only the start of 2011 and few high-demand hours have been observed yet. This is non-stationarity from the system's growth between 2011 and 2012, not a flaw in the factor representation.

The coefficient stability table (sorted by |mean|/sd) tells a clearer story than the raw coefficients alone:

- **RC1_heat (mean = +1.03, |mean|/sd = 3.68)** is the single dominant predictor. It is more than four times more stable than any other factor, and its sign is consistent with the data: warm hours strongly increase the probability of being a high-demand hour.
- **RC6_hr_cos (mean = −0.48) and RC2_hr_sin (mean = −0.51)** are second-tier. Their magnitudes are similar but fold-to-fold variation is much larger (sd ≈ 0.55–0.63), which makes sense — the hour-of-day cycle is the same across folds, but its *relative* importance changes as the model sees different month mixes in each training window.
- **RC3_calendar (mean = +0.09)** has a small but reasonably stable coefficient: the workingday-vs-holiday axis separates high and low demand modestly.
- **RC5_mnth_sin (mean = −0.48) and RC4_weather (mean = −0.32)** are the least stable. Weather is partly absorbed by RC1_heat (temperature already carries seasonal information), which explains why its standalone coefficient swings across folds.

### ElasticNet regression on engineered features
Now we predict log1p(cnt) directly, with interactions designed around the three research dimensions: environmental, temporal, and calendar.
"""

# yr was cast to category earlier; we need numeric for the interactions
data_en = data.copy().sort_values("dteday").reset_index(drop=True)
data_en["yr"] = data_en["yr"].astype(int)

# Nonlinear temperature
data_en["temp_sq"] = data_en["temp"] ** 2

# Environmental interactions
data_en["temp_x_hum"]       = data_en["temp"]       * data_en["hum"]
data_en["weathersit_x_hum"] = data_en["weathersit"] * data_en["hum"]

# Calendar × temporal (commute pattern lives here)
data_en["workingday_x_hr_sin"] = data_en["workingday"] * data_en["hr_sin"]
data_en["workingday_x_hr_cos"] = data_en["workingday"] * data_en["hr_cos"]
data_en["holiday_x_hr_sin"]    = data_en["holiday"]    * data_en["hr_sin"]
data_en["holiday_x_hr_cos"]    = data_en["holiday"]    * data_en["hr_cos"]

# Calendar × environmental
data_en["workingday_x_temp"] = data_en["workingday"] * data_en["temp"]

# Year × seasonality
data_en["yr_x_mnth_sin"] = data_en["yr"] * data_en["mnth_sin"]
data_en["yr_x_mnth_cos"] = data_en["yr"] * data_en["mnth_cos"]

features_environmental = ["temp", "hum", "windspeed", "weathersit", "temp_sq",
                          "temp_x_hum", "weathersit_x_hum"]
features_temporal      = ["hr_sin", "hr_cos", "mnth_sin", "mnth_cos", "yr",
                          "yr_x_mnth_sin", "yr_x_mnth_cos"]
features_calendar      = ["workingday", "holiday",
                          "workingday_x_hr_sin", "workingday_x_hr_cos", "workingday_x_temp",
                          "holiday_x_hr_sin", "holiday_x_hr_cos"]

feature_cols_en = features_environmental + features_temporal + features_calendar
dimension_map   = (["environmental"] * len(features_environmental)
                   + ["temporal"]    * len(features_temporal)
                   + ["calendar"]    * len(features_calendar))

X_en = data_en[feature_cols_en].astype(float).values
y_en = np.log1p(data_en["cnt"].astype(float).values)

alphas    = np.logspace(-2, 1, 6)
l1_ratios = [0.3, 0.45, 0.5, 0.7, 0.9, 1.0]
param_grid = [(a, l) for a in alphas for l in l1_ratios]

tscv  = TimeSeriesSplit(n_splits=5)
folds = list(tscv.split(X_en))

cv_rmse = np.full((len(param_grid), len(folds)), np.nan)
cv_r2   = np.full((len(param_grid), len(folds)), np.nan)

for i, (alpha_val, l1_val) in enumerate(param_grid):
    for j, (tr_idx, va_idx) in enumerate(folds):
        Xtr, Xva = X_en[tr_idx], X_en[va_idx]
        ytr, yva = y_en[tr_idx], y_en[va_idx]

        sc = StandardScaler().fit(Xtr)
        Xtr_s, Xva_s = sc.transform(Xtr), sc.transform(Xva)

        en = ElasticNet(alpha=alpha_val, l1_ratio=l1_val,
                        max_iter=10000, tol=1e-4, random_state=42).fit(Xtr_s, ytr)
        pred = en.predict(Xva_s)
        cv_rmse[i, j] = np.sqrt(mean_squared_error(yva, pred))
        cv_r2[i, j]   = r2_score(yva, pred)

mean_rmse = cv_rmse.mean(axis=1)
mean_r2   = cv_r2.mean(axis=1)
best_idx  = np.argmin(mean_rmse)
best_alpha, best_l1 = param_grid[best_idx]

print(f"Best alpha: {best_alpha:.5f}, l1_ratio: {best_l1:.2f}")
print(f"CV RMSE (log1p scale): {mean_rmse[best_idx]:.4f}, R²: {mean_r2[best_idx]:.4f}")

# Final fit on full sample with the best hyperparameters
sc_full  = StandardScaler().fit(X_en)
X_en_s   = sc_full.transform(X_en)
en_final = ElasticNet(alpha=best_alpha, l1_ratio=best_l1,
                      max_iter=10000, tol=1e-4, random_state=42).fit(X_en_s, y_en)

coef_df = pd.DataFrame({
    "feature":   feature_cols_en,
    "dimension": dimension_map,
    "coef":      en_final.coef_,
    "abs_coef":  np.abs(en_final.coef_),
})
coef_df["selected"] = coef_df["coef"] != 0

dim_summary = coef_df.groupby("dimension").agg(
    n_features     = ("feature",  "count"),
    n_selected     = ("selected", "sum"),
    total_abs_coef = ("abs_coef", "sum"),
).round(3)
dim_summary["pct_of_total_magnitude"] = (
    dim_summary["total_abs_coef"] / dim_summary["total_abs_coef"].sum() * 100
).round(1)

# n_features here is "features designed in each dimension" (7 per dimension by construction),
# n_selected is "non-zero coefficients in each dimension". They are equal because the
# CV-optimal hyperparameters give almost no L1 shrinkage (see markdown below).
print(f"Total features designed: {len(coef_df)}  |  non-zero coefficients: {int(coef_df['selected'].sum())}\n")
print(dim_summary)
print()
print(coef_df.sort_values("abs_coef", ascending=False).round(4).to_string(index=False))

"""**Why some features were dropped**

19 of 21 coefficients are non-zero — `hum` and `holiday_x_hr_sin` got zeroed out. The stronger lasso component (alpha = 0.01, l1_ratio = 0.30) was enough to drop features whose information was already captured by interactions: `hum` is absorbed by `weathersit_x_hum` and `temp_x_hum`, and `holiday_x_hr_sin` carries less signal than its cosine counterpart. The "selected" column is now informative, unlike in the previous near-ridge fit.

**Coefficient interpretation (standardized features, target = log1p(cnt))**

- **hr_sin (−0.75), hr_cos (−0.60)** — daily cycle, the largest effect.
- **temp (+0.45), temp_sq (−0.35)** — inverted-U: demand rises with temperature but flattens at the hottest values.
- **yr (+0.23)** — year-over-year system growth (2012 > 2011).
- **weathersit_x_hum (−0.17)** — bad weather combined with high humidity is the main weather signal; standalone `hum` was redundant.
- **mnth_sin (−0.16), mnth_cos (−0.14)** — secondary seasonal cycle.
- **Calendar interactions** (`workingday_x_hr_cos −0.14`, `workingday_x_temp −0.13`, `workingday +0.09`, `workingday_x_hr_sin +0.07`) — calendar acts almost entirely through interactions with hour and temperature, not as an independent driver.

**Dimension shares**: temporal 54.4%, environmental 32.1%, calendar 13.5%.

## Comparing the two approaches

The two methods rank the dominant dimension differently. Logistic regression on rotated factors puts **RC1_heat** at the top (|mean|/sd = 3.68), with hour-of-day second; elastic net puts **hr_sin and hr_cos** first, with `temp` and `temp_sq` second. The disagreement is mechanical: varimax merged temperature and the annual cycle into a single factor, inflating RC1's apparent dominance, while elastic net keeps them as separate raw terms.

Both methods agree on the three drivers and on calendar being the weakest, and they agree with the unsupervised analysis — K-means and GMM separated cleanly on hour and temperature, while calendar surfaced only as a small holiday-specific GMM component.

The methods are complementary: logistic regression gives a clean dimensional ranking on orthogonal axes, while elastic net reveals that calendar effects act *through* interactions with hour and temperature (the standalone calendar coefficients are small; the interaction terms carry the signal). The CV R² of 0.53 on log1p(cnt) reflects exactly that interaction structure, which the orthogonal-factor model cannot reach.
"""